name: spam_email_classifier_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - setuptools=69.5.1
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pillow
  - scipy
  - pip
  - pip:
    - pycaret
    - ttkbootstrap
    - pyinstaller